export default {
  home_light: require('../assets/images/Home_light.png'),
  machine: require('../assets/images/machine.png'),
  contact: require('../assets/images/contact.png'),
  arrow_left_light: require('../assets/images/arrow_left_light.png'),
  eyeOpen: require('../assets/images/eyeOpen.png'),
  eyeClose: require('../assets/images/eyeClose.png'),
  warning: require('../assets/images/warning.png'),
  button_nextlogo: require('../assets/images/button_nextlogo.png'),
  filter_icon: require('../assets/images/filter_icon.png'),
  search: require('../assets/images/search.png'),
  dots: require('../assets/images/dots.png'),
  plus: require('../assets/images/plus.png'),
  export: require('../assets/images/export.png'),
  filter: require('../assets/images/filter.png'),
  dashboard: require('../assets/images/dashboard.png'),
  setting: require('../assets/images/setting.png'),
  invoice: require('../assets/images/invoice.png'),
  user: require('../assets/images/user.png'),
  calendar_light: require('../assets/images/calendar_light.png'),
  downArrow: require('../assets/images/downArrow.png'),
};
